#!BuildTag: serviced
FROM opensuse/leap:15.1
ENV container docker

ENV LANG en_US.UTF-8

RUN zypper -n install git-core wget tar m4
WORKDIR /opt
RUN git clone -b mb_new_schema https://github.com/andrii-suse/environs

WORKDIR /opt/environs
RUN bash -x .product/mb/branch/.install_dependencies.sh

ENTRYPOINT ["/usr/bin/tail", "-f", "/dev/null"]
