#!/usr/bin/python

# Copyright (C) 2006 Peter Poeml.  All rights reserved.
# This program is free software; it may be used, copied, modified
# and distributed under the terms of the GNU General Public Licence,
# either version 2, or (at your option) any later version.


import sys, os, MySQLdb

servername = sys.argv[1]
score = sys.argv[2]

passwd = open('/root/.mytop').read().split('=')[1].strip()

dbh = MySQLdb.connect('localhost', 'root', passwd, 'redirector')
cursor = dbh.cursor(MySQLdb.cursors.DictCursor)

sqlraw = 'update server set score=%s where identifier=%s'
cursor.execute(sqlraw, [score, servername])

cursor.close()
dbh.commit()
dbh.close()
